<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-2ED4479" ignored="0" name="Default test" tests="1" failures="1" timestamp="17 Jan 2019 18:35:25 GMT" time="4.907" errors="0">
  <testcase name="Getvalidation" time="4.813" classname="Com.API.GetTest.PostAPITest">
    <failure type="com.fasterxml.jackson.core.JsonParseException" message="Unexpected character (&amp;apos;&amp;lt;&amp;apos; (code 60)): expected a valid value (number, String, array, object, &amp;apos;true&amp;apos;, &amp;apos;false&amp;apos; or &amp;apos;null&amp;apos;)
 at [Source: &amp;lt;!DOCTYPE html&amp;gt;
&amp;lt;html lang=&amp;quot;en&amp;quot;&amp;gt;
&amp;lt;head&amp;gt;
&amp;lt;meta charset=&amp;quot;utf-8&amp;quot;&amp;gt;
&amp;lt;title&amp;gt;Error&amp;lt;/title&amp;gt;
&amp;lt;/head&amp;gt;
&amp;lt;body&amp;gt;
&amp;lt;pre&amp;gt;SyntaxError: Unexpected token &amp;amp;quot;&amp;lt;br&amp;gt; &amp;amp;nbsp; &amp;amp;nbsp;at parse (/app/node_modules/body-parser/lib/types/json.js:83:15)&amp;lt;br&amp;gt; &amp;amp;nbsp; &amp;amp;nbsp;at /app/node_modules/body-parser/lib/read.js:116:18&amp;lt;br&amp;gt; &amp;amp;nbsp; &amp;amp;nbsp;at invokeCallback (/app/node_modules/raw-body/index.js:262:16)&amp;lt;br&amp;gt; &amp;amp;nbsp; &amp;amp;nbsp;at done (/app/node_modules/raw-body/index.js:251:7)&amp;lt;br&amp;gt; &amp;amp;nbsp; &amp;amp;nbsp;at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:307:7)&amp;lt;br&amp;gt; &amp;amp;nbsp; &amp;amp;nbsp;at emitNone (events.js:105:13)&amp;lt;br&amp;gt; &amp;amp;nbsp; &amp;amp;nbsp;at IncomingMessage.emit (events.js:207:7)&amp;lt;br&amp;gt; &amp;amp;nbsp; &amp;amp;nbsp;at endReadableNT (_stream_readable.js:1059:12)&amp;lt;br&amp;gt; &amp;amp;nbsp; &amp;amp;nbsp;at _combinedTickCallback (internal/process/next_tick.js:138:11)&amp;lt;br&amp;gt; &amp;amp;nbsp; &amp;amp;nbsp;at process._tickCallback (internal/process/next_tick.js:180:9)&amp;lt;/pre&amp;gt;
&amp;lt;/body&amp;gt;
&amp;lt;/html&amp;gt;
; line: 1, column: 2]">
      <![CDATA[com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Unexpected token &quot;<br> &nbsp; &nbsp;at parse (/app/node_modules/body-parser/lib/types/json.js:83:15)<br> &nbsp; &nbsp;at /app/node_modules/body-parser/lib/read.js:116:18<br> &nbsp; &nbsp;at invokeCallback (/app/node_modules/raw-body/index.js:262:16)<br> &nbsp; &nbsp;at done (/app/node_modules/raw-body/index.js:251:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:307:7)<br> &nbsp; &nbsp;at emitNone (events.js:105:13)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:207:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:1059:12)<br> &nbsp; &nbsp;at _combinedTickCallback (internal/process/next_tick.js:138:11)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:180:9)</pre>
</body>
</html>
; line: 1, column: 2]
at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:462)
at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1624)
at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:689)
at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3776)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
at Com.API.GetTest.PostAPITest.Getvalidation(PostAPITest.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- Getvalidation -->
</testsuite> <!-- Default test -->
